name: awaku
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-262.2.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  watch_connectivity: ^0.1.6
  flutter_ftms:
    # path: ./../flutter_ftms
    git:
      url: https://github.com/hifiaz/flutter_ftms.git
      ref: main 
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1
  riverpod: ^2.3.6
  chart_sparkline: ^1.0.13
  health: ^7.0.1
  go_router: ^10.0.0
  equatable: ^2.0.5
  logger: ^2.0.1
  intl: ^0.18.1
  liquid_progress_indicator:
    git:
     url: https://github.com/Jollastro/liquid_progress_indicator.git
  stop_watch_timer: ^3.0.1
  flutter_local_notifications: ^16.0.0-dev.1
  firebase_messaging: ^14.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  riverpod_generator: ^2.2.4
  build_runner: ^2.4.6
  custom_lint: ^0.4.0
  riverpod_lint: ^1.4.0
  freezed: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
